Feature/drag and drop functionality
TTFM-Labs/turntable pull request #145
Opened 2020-11-23 15:11 UTC by JaHajRF

drag and drop, move to top functionalities added

2020-11-23 15:27 UTC, kowalski requested changes

2020-11-23 15:27 UTC, kowalski commented on packages/webapp/src/components/SongsList/SongsList.component.tsx
> +  const onDragEnd = (result: DropResult): undefined => {
correct way is:

```
  const onDragEnd = React.useCallback((result: DropResult): undefined => {
   if (!result.destination) return
   setPlaylist(playlist => reorderList(playlist, result.source.index, result.destination.index))
  }, [setPlaylist])
```

...
        <DragDropContext onDragEnd={onDragEnd}>
```

This last part - using arrow function inside JSX is a recurring pattern in your code. You have be aware that each time you do it, you make it impossible to React to figure out that the component's props haven't changed, therefore it doesn't need to re-render
```

2020-11-23 15:27 UTC, kowalski commented on packages/webapp/src/pages/Audius.tsx
> +          Dispatch play song
This should happen without click of the button right?
Basically if you take a DJ seat and there is no song currently playing you should `dispatch(playerActions.initialPlay())`

2020-11-23 15:32 UTC, JaHajRF commented on packages/webapp/src/pages/Audius.tsx
> +          Dispatch play song
It is going to be addressed in future commits

2020-11-23 16:56 UTC, kowalski approved these changes

2020-11-24 09:08 UTC, kowalski commented on packages/webapp/src/components/SongsList/SongsList.component.tsx
> +    (result: DropResult): undefined => {
`void` not `undefined`

2020-11-24 09:09 UTC, kowalski approved these changes

2020-11-24 09:24 UTC, merged