Feature/napster config
TTFM-Labs/turntable pull request #194
Opened 2020-12-04 14:43 UTC by JaHajRF

added napster search.
room configuration added based on url

2020-12-04 15:14 UTC, kowalski requested changes

2020-12-04 15:14 UTC, kowalski commented on packages/webapp/src/store/consts/actionTypes.ts
> +export enum Provider {
`MusicProvider` ? 

Provider is a very abigious name. Like "item" or "data" ;)

2020-12-04 15:14 UTC, kowalski commented on packages/webapp/src/store/provider/provider.saga.ts
> +      return 'http://api.napster.com/v2.2/search?'
is there no way to search over https?
Our staging is on https, so if you try to fetch a resource from http it will fail with security exception.

2020-12-04 17:31 UTC, kowalski approved these changes

2020-12-07 19:03 UTC, kowalski approved these changes

2020-12-09 15:25 UTC, kowalski commented on packages/webapp/src/pages/TurntableRoom.tsx
> +      <ChooseUser
note for future: this should have a route on it's own

2020-12-09 15:30 UTC, kowalski commented on packages/webapp/src/store/musicProvider/musicProvider.saga.ts
> +    )) as Result<NapsterReturnType>
here we are just trusting napster to return the right shape of data.
It's not guaranteed that it will.

There is a way to check things like this on runtime without too much additional work.
All it takes is that you implement `NapsterReturnType` as class instead of interface.
This allows you to do:

```
const checkedResult = plainToClass(NapsterReturnType, plainResult)
```
were plainResult is what we get directly form external service

plainToClass from from `class-transformer`, it's what we use in nest backend

2020-12-09 15:32 UTC, kowalski commented on packages/webapp/src/store/musicProvider/musicProvider.saga.ts
> +    debounce(250, MusicProvider.FETCH_TRACK_LIST, (payload: MusicProviderTrackActions['fetch']) =>
Btw, I see you are doing this all over the place.
I mean you could do just
```
debounce(250, MusicProvider.FETCH_TRACK_LIST, fetchTrackList)
```
right? 

Without the extra arrow function. Any particular reason you're doing this?

2020-12-09 15:34 UTC, JaHajRF commented on packages/webapp/src/pages/TurntableRoom.tsx
> +      <ChooseUser
We have it on the same page, to prevent error on initial music play. User has to interact with page before music starts, so that is why we have it on the same page.

2020-12-09 15:38 UTC, JaHajRF commented on packages/webapp/src/store/musicProvider/musicProvider.saga.ts
> +    debounce(250, MusicProvider.FETCH_TRACK_LIST, (payload: MusicProviderTrackActions['fetch']) =>
There is an arrow function to provide properties to saga generator, in this case MusicProviderTrackAction payload

2020-12-09 15:40 UTC, kowalski commented on packages/webapp/src/store/musicProvider/musicProvider.selector.ts
> +const storeEndpoint = (s: AnyProps): GenericStore<string> => s[keyNames.musicProviderEndpoint] as GenericStore<string>
Note for future:

This is quite ugly that we need to type it like here.

The fix for this is as follows.

1. In `src/store/index.ts` move this block to module level
```
    export const combinedReducer = combineReducers<Reducer<CombinedReducer, any>>({
      ...rootReducer,
    }),
```

2. Define `src/store/store.types` and inside do:

```
import { combinedReducer } from './index'

export type StoreState = ReturnType<typeof combinedReducer>
```

3. This will allow you to rephrase this line (and other like this simply as)

```
const storeEndpoint = (s: StoreState) => s[keyNames.musicProviderEndpoint]
```

This will correctly infer the type from global definition. No need for the `as GenericStore<string>` anymore

2020-12-09 15:40 UTC, kowalski approved these changes

2020-12-09 15:43 UTC, merged

2020-12-09 15:50 UTC, kowalski commented on packages/webapp/src/pages/TurntableRoom.tsx
> +      <ChooseUser
Ah, so you're saying that the change of URL will invalidate the click from the user? 
That's odd. I would expect that it's still considered the same page, because React overrides browserHistory and prevents full page reload. But maybe it's more tricky that I give it credit for

2020-12-09 15:51 UTC, kowalski commented on packages/webapp/src/store/musicProvider/musicProvider.saga.ts
> +    debounce(250, MusicProvider.FETCH_TRACK_LIST, (payload: MusicProviderTrackActions['fetch']) =>
I doubt you need this. The default behavior is to pass the action to the saga function.