Configuration of signaling server
TTFM-Labs/turntable pull request #205
Opened 2020-12-08 09:36 UTC by bobobob22

2020-12-08 15:33 UTC, JaHajRF requested changes

2020-12-08 15:33 UTC, JaHajRF commented on packages/common-store/src/store/initState/initState.reducer.ts
> +  public peerIdJson: UserJson | {} = {}
Would not call it peerIdJson as well.

2020-12-08 15:33 UTC, JaHajRF commented on packages/common-store/src/store/peerId/peerId.reducer.ts
> +export type InitStateActions = ActionsType<typeof peerIdActions>
It should be PeerIdActions

2020-12-08 15:33 UTC, JaHajRF commented on packages/common-store/src/store/peerId/peerId.reducer.ts
> +  public peerIdJson: PeerIdJson | null = null
You are storing the same property in InitStateStore. What is the differenace between them? I guess one of them should be renamed to avoid confussion.

2020-12-08 15:33 UTC, JaHajRF commented on packages/common-store/src/store/player/player.saga.ts
> +  const userPeerId = (yield select(peerIdJson)) as PeerIdJson
I think better approach would be to import peerIdSelector, then: 
`yield select(peerIdSelector.peerIdJson)`

Just peerIdJson suggest that this is a value. not a selector

2020-12-08 15:33 UTC, JaHajRF commented on packages/webapp/src/components/DjSeat/DjSeat.test.tsx
> +  it('should match inline snapshot', async () => {
Is async needed?

2020-12-08 15:33 UTC, JaHajRF commented on packages/webapp/src/utils/getMyPeerId.ts
> +}
Should this file be removed as we get peerId from selector?

2020-12-08 15:53 UTC, JaHajRF commented on packages/common-store/src/store/peerId/peerId.reducer.ts
> +    state.peerIdJson = action.payload.toJSON()
I guess we dont need two actions here, as we can move `toJSON()` to action call

2020-12-09 09:07 UTC, bobobob22 commented on packages/common-store/src/store/dancefloor/dancefloor.selector.ts
> +    // if (!dancefloorMap) {
ok

2020-12-09 09:09 UTC, bobobob22 commented on packages/webapp/src/utils/getMyPeerId.ts
> +}
ok

2020-12-09 09:10 UTC, bobobob22 commented on packages/webapp/src/components/DjSeat/DjSeat.test.tsx
> +  it('should match inline snapshot', async () => {
ok

2020-12-09 09:12 UTC, bobobob22 commented on packages/common-store/src/store/peerId/peerId.reducer.ts
> +export type InitStateActions = ActionsType<typeof peerIdActions>
ok

2020-12-09 09:14 UTC, bobobob22 commented on packages/common-store/src/store/djSeats/djSeats.selector.ts
> +    return userPeerId?.id === playingDjPeerId
ok

2020-12-09 09:16 UTC, bobobob22 commented on packages/common-store/src/store/initState/initState.reducer.ts
> +  pubKey: string
ok

2020-12-09 09:17 UTC, bobobob22 commented on packages/common-store/src/store/initState/initState.reducer.ts
> +  public peerIdJson: UserJson | {} = {}
ok, it is called `PeerInfo` now

2020-12-09 09:21 UTC, bobobob22 commented on packages/common-store/src/store/player/player.saga.ts
> +  const userPeerId = (yield select(peerIdJson)) as PeerIdJson
ok

2020-12-09 09:44 UTC, bobobob22 commented on packages/common-store/src/store/peerId/peerId.reducer.ts
> +  public peerIdJson: PeerIdJson | null = null
ok

2020-12-09 11:09 UTC, JaHajRF approved these changes

2020-12-09 11:16 UTC, merged