Feat: Sign up page functionality
TTFM-Labs/turntable pull request #223
Opened 2020-12-11 15:24 UTC by mariusjagminas

2020-12-11 15:49 UTC, kowalski requested changes
Once you add validation for individual fields it's a good idea to display the error messages.

The `useForm` hook gives you `errors` object, that has an error for each field.
So you could extend <TextInput>  to get the optional `error` prop and pass it like:

```
              error={errors.email?.message}

```

2020-12-11 15:49 UTC, kowalski commented on packages/webapp/src/store/session/session.saga.ts
> +  const regex = new RegExp(/confirm-email[\S\s]*/)
Can't we include the confirm-email route in `whitelistedRoutes`? 
You could have `whilelistedRoutes` be a a list of Regexps and do sth like:

```
return Boolean(routes.find((regexp) => regex.test(pathname))
```

2020-12-11 15:49 UTC, kowalski commented on packages/webapp/src/pages/SignUp/SignUp.tsx
> +          render={({ onChange }) => <TextInput onChange={onChange} placeholder="Email" />}
I think you should also be passing `value` and `onBlur` to all `<TextInput>`

2020-12-11 15:49 UTC, kowalski commented on packages/webapp/src/pages/SignUp/SignUp.tsx
> +          name="email"
Would be nice to validate that this is an email.

Something like
```
          rules={{
            required: 'This field is required',
            pattern: {
              value: emailRegexp,
              message: 'Is not a correct email address',
            },
          }}
```
```
const emailRegexp = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;
```

2020-12-11 15:49 UTC, kowalski commented on packages/webapp/src/pages/SignUp/SignUp.tsx
> +          name="confirmPassword"
you should validate that confirm matches password.

You can do it like:

```
          rules={{ validate: validateConfirmation }}
```

```
  const validateConfirmation = (value: string) => {
    if (value !== watch('email')) return 'Passwords do not match';
  };

```

(`watch` is part of `useForm` result)

2020-12-11 16:09 UTC, mariusjagminas commented on packages/webapp/src/pages/SignUp/SignUp.tsx
> +          render={({ onChange }) => <TextInput onChange={onChange} placeholder="Email" />}
Console displays an error "Warning: A component is changing an uncontrolled input of type text to be controlled" when I pass `value` to <TextInput/> .I should figure out how to set initial value as an empty string to overcome this error.

2020-12-11 16:13 UTC, mariusjagminas commented on packages/webapp/src/pages/SignUp/SignUp.tsx
> +          name="confirmPassword"
I do that in `onSubmitHandler` function
 ```
 try {
      if (password !== confirmPassword) {
        throw new Error(ErrorMsg.PASSWORDS_DONT_MATCH)
      }
```

2020-12-11 16:20 UTC, kowalski commented on packages/webapp/src/pages/SignUp/SignUp.tsx
> +          render={({ onChange }) => <TextInput onChange={onChange} placeholder="Email" />}
a, that's easy, add `defaultValue=''` to Controller

2020-12-11 16:21 UTC, kowalski commented on packages/webapp/src/pages/SignUp/SignUp.tsx
> +          name="confirmPassword"
It's better to use react-hook library as it was intendented by their creators.
The validation is done way before submit.
Submit is not even possible if any of the fields have error.

2020-12-14 12:58 UTC, kowalski approved these changes

2020-12-14 13:52 UTC, merged