Feature/avatar message pop up
TTFM-Labs/turntable pull request #246
Opened 2020-12-16 16:40 UTC by JaHajRF

avatar pop up messages added

2020-12-18 11:09 UTC, kowalski requested changes

2020-12-18 11:19 UTC, JaHajRF commented on packages/roomSync/src/services/config/protonsRequestMessage.ts
> +  required bytes shouldDisplayMessagePopUp = 8;
I'm still working on changes that were discussed during last call. This prop will be deleted in next commit.

2020-12-18 11:33 UTC, kowalski commented on packages/roomSync/src/services/config/protonsRequestMessage.ts
> +  required bytes shouldDisplayMessagePopUp = 8;
ok, great, I got confused as I'm doing few reviews at the same time ;p

2020-12-21 15:48 UTC, kowalski requested changes

2020-12-21 15:48 UTC, kowalski commented on packages/webapp/src/components/Chat/Chat.stories.tsx
> +  ] as Message[]
prefer:

```
const messages: Messages[] = [...]
```
without as

2020-12-21 15:48 UTC, kowalski commented on packages/webapp/src/components/DancefloorAvatar/DancefloorAvatar.styles.ts
> +// export const MessageBox = styled.div`
what the deal with all these commented out code?

2020-12-21 15:48 UTC, kowalski commented on packages/webapp/src/store/chatMessages/chatMessages.reducer.ts
> +      state.usersLastMessages.set(action.payload.from.peerId, action.payload)
no need to delete, than set; set overwrite previous value, right?

2020-12-21 15:48 UTC, kowalski commented on packages/webapp/src/store/chatMessages/chatMessages.saga.ts
> +  yield delay(4000)
magic number, move to const

2020-12-21 16:00 UTC, kowalski approved these changes

2020-12-21 16:03 UTC, merged