Feature satisfaction meter
TTFM-Labs/turntable pull request #260
Opened 2020-12-18 14:39 UTC by bobobob22

2020-12-18 16:21 UTC, kowalski requested changes

2020-12-18 16:21 UTC, kowalski commented on packages/roomSync/src/store/djSeats/djSeats.reducer.ts
> +      state.djSeats.get(action.payload.djSeatKey)!.djPoints += action.payload.score
using `!` here could have unwanted consequences


If there is no matching key in the store you will effectively do `undefined.djPoints += action.payload.score` and get TypeError

do sth like:
````
const seat = state.djSeats.get(action.payload.djSeatKey)
if (seat) seat.djPoints += action.payload.score
```

2020-12-18 16:21 UTC, kowalski commented on packages/roomSync/src/store/djSeats/djSeats.saga.ts
> +const voteTypes = {
This would look better as `enum`

2020-12-18 16:21 UTC, kowalski commented on packages/roomSync/src/store/djSeats/djSeats.saga.ts
> +export function* onSatisfactionSend(action: SatisfactionMeterActions['updateSatisfaction']): Generator {
It doesn't seem you've added a test for this saga in `djSeats.saga.test.ts`

2020-12-18 16:21 UTC, kowalski commented on packages/roomSync/src/store/satisfactionMeter/satisfactionMeter.reducer.ts
> +  updateOnlySatisfaction: createAction<number>(SatisfactionMeter.ON_SATISFACTION_ONLY_UPDATE),
Is think action needed?

You could just make `UpdateSatisfaction.choice` optional and not update it if it's not specified in `action.payload`, thus having only `updateSatisfaction` action

2020-12-18 16:21 UTC, kowalski commented on packages/webapp/src/store/webPlayer/webPlayer.saga.ts
> +  yield put(satisfactionMeterActions.updateOnlySatisfaction(4))
`4` is a very critptic magic number
makes me think about how many sons Dawid from old testament had
or maybe it has something to do with astrology ;)

2020-12-18 16:21 UTC, kowalski commented on packages/webapp/src/store/user/user.saga.ts
> +const voteTypes = {
```
export enum Vote {
   approve: 1
   disapprove: -1
}
```

if you do it like this you don't need to have extra logic for translating enum to number

2020-12-18 16:21 UTC, kowalski commented on packages/webapp/src/store/user/user.saga.ts
> +export function* handleSongEnd(): Generator {
that's a slight misues of saga imo

You are receiving an action and put other action. Than you listen of that other action in reducer to make an update.

But you could save yourself trouble and just listen on original action in reducer and not do anything in saga ,right?

2020-12-18 16:21 UTC, kowalski commented on packages/webapp/src/store/user/user.saga.ts
> +  yield put(userActions.updateUserScore({ score }))
it looks like here you are giving points to user who is voting
score change should affect DJ that is playing current song, not the user that is doing the vote

2020-12-18 16:21 UTC, kowalski commented on packages/webapp/src/store/user/user.reducer.ts
> +  public userPoints: number = 0
I'm not even sure we want to store "our" points seperately.
This should just be part of structure of dancefloorAvatar (dj's are there as well, right?)

2020-12-21 09:17 UTC, bobobob22 commented on packages/roomSync/src/store/djSeats/djSeats.reducer.ts
> +      state.djSeats.get(action.payload.djSeatKey)!.djPoints += action.payload.score
ok

2020-12-21 15:58 UTC, bobobob22 commented on packages/roomSync/src/store/satisfactionMeter/satisfactionMeter.reducer.ts
> +  updateOnlySatisfaction: createAction<number>(SatisfactionMeter.ON_SATISFACTION_ONLY_UPDATE),
ok

2020-12-21 15:59 UTC, bobobob22 commented on packages/webapp/src/store/user/user.saga.ts
> +const voteTypes = {
ok

2020-12-21 15:59 UTC, bobobob22 commented on packages/webapp/src/store/user/user.saga.ts
> +  yield put(userActions.updateUserScore({ score }))
ok

2020-12-21 15:59 UTC, bobobob22 commented on packages/webapp/src/store/user/user.reducer.ts
> +  public userPoints: number = 0
ok

2020-12-21 15:59 UTC, bobobob22 commented on packages/roomSync/src/store/djSeats/djSeats.saga.ts
> +const voteTypes = {
ok

2020-12-21 15:59 UTC, bobobob22 commented on packages/webapp/src/store/webPlayer/webPlayer.saga.ts
> +  yield put(satisfactionMeterActions.updateOnlySatisfaction(4))
ok ;)

2020-12-21 17:18 UTC, kowalski requested changes

2020-12-21 17:18 UTC, kowalski commented on packages/roomSync/src/services/config/protonsRequestMessage.ts
> +  required bytes avatarId = 5;
what is avatarId here for ? 
Didn't you mean something like peerId ?

2020-12-21 17:18 UTC, kowalski commented on packages/roomSync/src/store/dancefloor/dancefloor.types.ts
> +  score?: number
you can remove this; we're not doing this for now

2020-12-21 17:18 UTC, kowalski commented on packages/roomSync/src/store/player/player.saga.ts
> +export function* sendSatisfactionHandler(): Generator {
imo this belongs in satisfactionMeter.saga

2020-12-21 17:18 UTC, kowalski commented on packages/roomSync/src/store/satisfactionMeter/satisfactionMeter.reducer.ts
> +  public approvedAvatarIds: string[] = []
avatarId is just an idea of the avatar. Many users can have same avatar.

2020-12-21 17:18 UTC, kowalski commented on packages/roomSync/src/store/satisfactionMeter/satisfactionMeter.reducer.ts
> +  public approvedAvatarIds: string[] = []
So you probably need a `Set` of `peerId`

2020-12-21 17:18 UTC, kowalski commented on packages/roomSync/tsconfig.json
> +    "isolatedModules": true,
why this change?

2020-12-21 17:21 UTC, kowalski commented on packages/webapp/src/components/SatisfactionMeter/SatisfactionMeter.component.tsx
> +  const bulbsList = [...bulbsMap.values()].map((value, index) => {
it's probably a good idea to wrap this in `React.useMemo`

2020-12-22 10:40 UTC, bobobob22 commented on packages/roomSync/src/store/satisfactionMeter/satisfactionMeter.reducer.ts
> +  public approvedAvatarIds: string[] = []
ok

2020-12-22 10:40 UTC, bobobob22 commented on packages/roomSync/tsconfig.json
> +    "isolatedModules": true,
unnecessary

2020-12-22 10:40 UTC, bobobob22 commented on packages/webapp/src/components/SatisfactionMeter/SatisfactionMeter.component.tsx
> +  const bulbsList = [...bulbsMap.values()].map((value, index) => {
ok

2020-12-22 10:41 UTC, bobobob22 commented on packages/roomSync/src/store/dancefloor/dancefloor.types.ts
> +  score?: number
ok

2020-12-22 10:42 UTC, bobobob22 commented on packages/roomSync/src/services/config/protonsRequestMessage.ts
> +  required bytes avatarId = 5;
ok

2020-12-22 10:52 UTC, bobobob22 commented on packages/roomSync/src/store/player/player.saga.ts
> +export function* sendSatisfactionHandler(): Generator {
ok

2020-12-22 12:10 UTC, bobobob22 commented on packages/roomSync/src/store/player/player.saga.ts
> +export function* sendSatisfactionHandler(): Generator {
ok

2020-12-22 17:06 UTC, bobobob22 commented on packages/roomSync/src/store/djSeats/djSeats.saga.ts
> +export function* onSatisfactionSend(action: SatisfactionMeterActions['updateSatisfaction']): Generator {
ok

2020-12-22 17:06 UTC, bobobob22 commented on packages/webapp/src/store/user/user.saga.ts
> +export function* handleSongEnd(): Generator {
ok

2020-12-23 16:05 UTC, kowalski approved these changes

2020-12-23 16:05 UTC, merged