feature/change-volume-component
TTFM-Labs/turntable pull request #262
Opened 2020-12-21 09:14 UTC by JaHajRF

volume bar changed to fit new design and set volume in store

2020-12-21 09:43 UTC, kowalski requested changes

2020-12-21 09:43 UTC, kowalski commented on packages/webapp/src/components/NavBar/NavBar.types.ts
> +  setWebPlayerVolume: (volume: number) => WebPlayerActions['setVolume']
is this right typing ? 
imo it should be 
```
(volume: number) => void
```
no?

2020-12-21 09:43 UTC, kowalski commented on packages/webapp/src/store/webPlayer/webPlayer.saga.ts
> +  const playedSong = (yield select(webPlayerSelectors.playedSong)) as HTMLAudioElement | null
btw, these `as HTMLAudioElement | null` are bugging me

Can we add typed-redux-saga ?

2020-12-21 10:46 UTC, JaHajRF commented on packages/webapp/src/components/NavBar/NavBar.types.ts
> +  setWebPlayerVolume: (volume: number) => WebPlayerActions['setVolume']
I used to set it as void but I've changed that here. My reasoning:

In container it is typed as: 
`const setWebPlayerVolume = (volume: number): WebPlayerActions['setVolume'] =>
    dispatch(webPlayerActions.setVolume(volume))`

So I've followed useDispatch typing and: 
`export interface Dispatch<A extends Action = AnyAction> {
  <T extends A>(action: T): T
}`

as dispatch returns action object I assumed that would be proper typing.

Both ways are valid for compiler.
What do you think?

2020-12-21 10:47 UTC, JaHajRF commented on packages/webapp/src/store/webPlayer/webPlayer.saga.ts
> +  const playedSong = (yield select(webPlayerSelectors.playedSong)) as HTMLAudioElement | null
Ok I will make github issue and work on that

2020-12-22 10:47 UTC, kowalski approved these changes

2020-12-22 10:53 UTC, merged