Feature: saving username and avatar
TTFM-Labs/turntable pull request #267
Opened 2020-12-21 15:23 UTC by mariusjagminas

2020-12-21 17:11 UTC, kowalski requested changes

2020-12-21 17:11 UTC, kowalski commented on packages/webapp/src/pages/AvatarSelection/AvatarSelection.page.tsx
> +        id={String(index + 1)}
id should be taken from avatar map. The key of the map is the id. It's coincidence that we used integer values in there.

2020-12-21 17:11 UTC, kowalski commented on packages/webapp/src/pages/TurntableRoom.tsx
> +      dispatch(initStateActions.initializeRoom({ avatarId }))
no need to pass `avatarId` here

2020-12-21 17:11 UTC, kowalski commented on packages/webapp/src/store/user/user.saga.test.ts
> +      saga
please don't add tests to codebase of this type. 

Please grep for `expectSaga` and make a test of this type for all new saga tests.

2020-12-21 17:23 UTC, mariusjagminas commented on packages/roomSync/src/store/initState/initState.reducer.ts
> +  initializeRoom: createAction<{ avatarId: string }>(InitState.INITIALIZE_ROOM),
I'm not sure if it is good idea. avatarId is located in packages/webpapp/. So package/roomSync will be using webapp store. Or is it ok. Maybe I'm missing something .

2020-12-21 17:36 UTC, kowalski commented on packages/roomSync/src/store/initState/initState.reducer.ts
> +  initializeRoom: createAction<{ avatarId: string }>(InitState.INITIALIZE_ROOM),
Ah, now I understand.
Ok I see your point.

So this saga is using `avatarId` to do this:

```
  const dancefloorAvatar = {
    avatarId,	    avatarId,
    isDancing: false,	    isDancing: false,
    positionX: avatarPosition.positionX,	    positionX: avatarPosition.positionX,
    positionY: avatarPosition.positionY,	    positionY: avatarPosition.positionY,
    userPeerId: userPeerId.id,	    userPeerId: userPeerId.id,
  } as DancefloorAvatar	  } as DancefloorAvatar
  yield put(dancefloorActions.addAvatarToDancefloor(dancefloorAvatar))	  yield put(dancefloorActions.addAvatarToDancefloor(dancefloorAvatar))
```

Basically move dispatching this action out of this saga. You can even dispatch it from `TurntableRoom` screen (same place where the `initializeRoom` is dispatched from. 
This way you will untangle these two.

2020-12-22 10:22 UTC, kowalski commented on packages/webapp/src/pages/AvatarSelection/AvatarSelection.page.tsx
> +  useEffect(() => {
I don't get it, why do we have this crossdependency between errors on username and avatarId ? 
These should be two independent fields, both required.

2020-12-22 10:24 UTC, kowalski commented on packages/webapp/src/pages/AvatarSelection/AvatarSelection.page.tsx
> +      <Controller
You are rendering a `Controller` for each avatar, as you are inside `map()` over `avatarsMap`

Instead you should have just one controller and in `render` pass a component that does the map over avatars.

2020-12-22 10:25 UTC, mariusjagminas commented on packages/webapp/src/pages/AvatarSelection/AvatarSelection.page.tsx
> +  useEffect(() => {
Because both errors are displayed under username input field.

2020-12-22 10:26 UTC, kowalski commented on packages/webapp/src/pages/AvatarSelection/AvatarSelection.page.tsx
> +  useEffect(() => {
so much easier than manipulating state would be to just display them both

2020-12-22 10:29 UTC, mariusjagminas commented on packages/webapp/src/pages/AvatarSelection/AvatarSelection.page.tsx
> +      <Controller
That was the easiest way to implement useForms in this existing component. Probably that component should be rebuilt from scratch because now it is not possible implement form easily in to it.

2020-12-22 16:18 UTC, kowalski approved these changes

2020-12-23 11:41 UTC, merged