create playlist
TTFM-Labs/turntable pull request #309
Opened 2021-01-08 15:30 UTC by bobobob22

2021-01-14 15:52 UTC, kowalski requested changes

2021-01-14 15:52 UTC, kowalski commented on packages/webapp/src/store/router/router.saga.ts
> +  // yield history.push(action.payload)
intentional change?

2021-01-14 15:52 UTC, kowalski commented on packages/webapp/src/store/uploadSongs/uploadSongs.reducer.ts
> +      state.songs = [...prevSongs, action.payload]
you don't need this unpacking
reduxjs/toolkit uses internally `immer` that ensures this

its sufficient to do:
```
state.songs.push(action.payload)
```

2021-01-14 15:52 UTC, kowalski commented on packages/webapp/src/store/uploadSongs/uploadSongs.reducer.ts
> +      state.songs = [...prevSongs, action.payload]
same applies to other actions in this reducer

2021-01-14 15:52 UTC, kowalski commented on packages/webapp/src/store/uploadSongs/uploadSongs.saga.ts
> +  const promise = new Promise<TagType>((resolve, reject) => {
actually you could just be doing 
```
return new Promise(....)
```

without this
```
 const data = await promise

  return data
```
this two lines have literally no effect

2021-01-14 15:52 UTC, kowalski commented on packages/webapp/src/store/uploadSongs/uploadSongs.saga.ts
> +
do we want to return here?
perhaps we should put progress to 100 first?

2021-01-14 15:52 UTC, kowalski commented on packages/webapp/src/store/uploadSongs/uploadSongs.selector.ts
> +      ...songsProgressArray.find((progress) => progress.id === song.id),
wouldn't it be easier if `songsProgressArray` is a `Map<number, ISongProgress>` ?

2021-01-14 15:52 UTC, kowalski commented on packages/webapp/src/store/uploadSongs/uploadSongs.selector.ts
> +      ...songsProgressArray.find((progress) => progress.id === song.id),
(and therefore is called `songsProgressMap`

2021-01-15 09:38 UTC, bobobob22 commented on packages/webapp/src/store/uploadSongs/uploadSongs.reducer.ts
> +      state.songs = [...prevSongs, action.payload]
ok

2021-01-15 09:42 UTC, bobobob22 commented on packages/webapp/src/store/uploadSongs/uploadSongs.saga.ts
> +  const promise = new Promise<TagType>((resolve, reject) => {
ok

2021-01-15 09:43 UTC, bobobob22 commented on packages/webapp/src/store/uploadSongs/uploadSongs.saga.ts
> +
ok

2021-01-19 10:00 UTC, bobobob22 commented on packages/webapp/src/store/uploadSongs/uploadSongs.selector.ts
> +      ...songsProgressArray.find((progress) => progress.id === song.id),
ok

2021-01-19 10:01 UTC, bobobob22 commented on packages/webapp/src/store/router/router.saga.ts
> +  // yield history.push(action.payload)
only for testing, i reversed it

2021-01-22 16:58 UTC, merged