add userId to socket requests
TTFM-Labs/turntable pull request #366
Opened 2021-01-21 13:01 UTC by bobobob22

2021-01-21 16:30 UTC, kowalski requested changes

2021-01-21 16:30 UTC, kowalski commented on packages/signaling-server/src/index.ts
> +  const PUB_KEY_URL = 'https://api.staging.tt.fm/auth/pub-key'
get this from env;
make a note to add this env to TaskDefinition in infrastracture repo

2021-01-21 16:30 UTC, kowalski commented on packages/roomSync/src/store/initState/initState.saga.ts
> +  console.log('3')
leftover

2021-01-21 16:30 UTC, kowalski commented on packages/signaling-server/src/helpers/configureListenersForRoomBroadcastSocketIo.ts
> +  roomBroadcast.addListenerToChatRoomBroadcast('removeAvatar', (data: IMessage & IDisconnectPeer) => io.emit('removeAvatar', data.userPeerId))
we are not passing `userId` in this message?

2021-01-21 16:30 UTC, kowalski commented on packages/signaling-server/src/index.ts
> +  const PUB_KEY_URL = 'https://api.staging.tt.fm/auth/pub-key'
take from env, add in TaskDefinition in infrastracture repo

2021-01-21 16:30 UTC, kowalski commented on packages/signaling-server/src/index.ts
> +    const connectedSocketId = socket.handshake.user.id
this is not socket id. This is userId. This variable name is confusing

2021-01-21 16:30 UTC, kowalski commented on packages/webapp/src/containers/Dancefloor.container.tsx
> +  const dispatchSendSatisfaction = (choice: string): void => {
useCallbacks with correct dependencies is welcome

2021-01-21 16:30 UTC, kowalski commented on packages/webapp/src/store/user/user.saga.test.ts
> +        broadcastActions.sendSatisfaction({ choice: 'approve', userId: '2', userPeerId: '2' }),
its passed as string here `'2'`. Isnt' userId `number` ?

2021-01-21 16:30 UTC, kowalski commented on packages/webapp/src/store/user/user.saga.ts
> +    userId.toString(),
action should get userId as number imo. No need for toString()

2021-01-22 08:22 UTC, kowalski commented on packages/signaling-server/package.json
> +    "@types/passport-jwt": "^3.0.3",
this one should be in devDependencies

2021-01-22 09:27 UTC, bobobob22 commented on packages/roomSync/src/store/initState/initState.saga.ts
> +  console.log('3')
ok

2021-01-22 09:27 UTC, bobobob22 commented on packages/signaling-server/src/index.ts
> +    const connectedSocketId = socket.handshake.user.id
ok

2021-01-22 09:27 UTC, bobobob22 commented on packages/webapp/src/store/user/user.saga.test.ts
> +        broadcastActions.sendSatisfaction({ choice: 'approve', userId: '2', userPeerId: '2' }),
ok

2021-01-22 09:27 UTC, bobobob22 commented on packages/webapp/src/store/user/user.saga.ts
> +    userId.toString(),
ok

2021-01-22 09:56 UTC, bobobob22 commented on packages/signaling-server/src/index.ts
> +  const PUB_KEY_URL = 'https://api.staging.tt.fm/auth/pub-key'
ok

2021-01-22 09:56 UTC, bobobob22 commented on packages/signaling-server/package.json
> +    "@types/passport-jwt": "^3.0.3",
ok

2021-01-22 11:41 UTC, merged